name: Build and Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  BUILD_TYPE: Release
  SDK_VERSION: 1.2.154.0

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build 
        working-directory: ${{runner.workspace}}
        run: |
          sudo apt-get install libsdl2-2.0-0 libsdl2-dev
          sudo -H pip3 install --upgrade pip setuptools 
          sudo -H pip3 install meson ninja 
          export SDK_VERSION=$(curl https://vulkan.lunarg.com/sdk/latest/linux.txt)
          wget --no-cookies -O sdk.tar.gz https://sdk.lunarg.com/sdk/download/${SDK_VERSION}/linux/vulkan_sdk.tar.gz
          tar -xf sdk.tar.gz
          source ${SDK_VERSION}/setup-env.sh
          cd $GITHUB_WORKSPACE
          CXX=g++-10 meson setup build --prefix="/" --bindir=bin
          meson compile -C build
          cd build
          meson test
          DESTDIR=${{runner.workspace}}/install meson install
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: hypnitro-linux
          path: ${{runner.workspace}}/install/bin/
  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build 
        working-directory: ${{runner.workspace}}
        run: |
          brew install sdl2
          sudo -H pip3 install --upgrade pip setuptools 
          sudo -H pip3 install meson ninja 
          export SDK_VERSION=$(curl https://vulkan.lunarg.com/sdk/latest/mac.txt)
          wget --no-cookies -O sdk.dmg https://sdk.lunarg.com/sdk/download/${SDK_VERSION}/mac/vulkan_sdk.dmg
          hdiutil attach sdk.dmg -mountpoint ${{runner.workspace}}/sdk
          cd sdk
          sudo ./install_vulkan.py
          cd $GITHUB_WORKSPACE
          hdiutil detach ${{runner.workspace}}/sdk
          meson setup build --prefix="/" --bindir=bin
          meson compile -C build
          cd build
          meson test
          DESTDIR=${{runner.workspace}}/install meson install
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: hypnitro-macos
          path: ${{runner.workspace}}/install/bin/
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup
        run: |
          C:\msys64\usr\bin\pacman -Syyu --noconfirm
          C:\msys64\usr\bin\pacman -S --noconfirm mingw-w64-x86_64-SDL2 mingw-w64-x86_64-pkg-config mingw-w64-x86_64-toolchain mingw-w64-x86_64-gcc mingw-w64-x86_64-python mingw-w64-x86_64-meson
          choco install vulkan-sdk
          choco uninstall strawberryperl
      - name: Build
        run: C:\msys64\usr\bin\bash -c 'export PATH=/c/msys64/mingw64/bin:${PATH} && echo $PATH && export SDK_VERSION=$(curl https://vulkan.lunarg.com/sdk/latest/windows.txt) && export VULKAN_SDK=/c/VulkanSDK/${SDK_VERSION} && cd /d/a/hypNITRO/hypNITRO && meson setup build --prefix="/" --bindir=bin && meson compile -C build && cd build && meson test && DESTDIR=/d/a/hypNITRO/install meson install' 
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: hypnitro-windows
          path: ${{runner.workspace}}/install/msys64/bin/
